[package]
name = "fluid_revenue"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.9.2", features = ["full"] }
tokio = {version="1.43.0", features=["macros","rt-multi-thread"]}
