[package]
name = "fluid_revenue"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.9.2", features = ["full"] }
clap = { version = "4.5.24", features = ["derive"] }
tokio = {version="1.43.0", features=["macros","rt-multi-thread"]}
